import glob
import hashlib
import os
import re

import bpy

from ..utils.timer_utils import TimerUtils
from ..utils.command_utils import CommandUtils
from ..utils.translate_utils import rpt_

from ..common.global_config import GlobalConfig
from ..common.global_config import LogicName

from ..games.efmi import ExportEFMI
from ..games.gimi import ExportGIMI
from ..games.himi import ExportHIMI
from ..games.identityv import ExportIdentityV
from ..games.snowbreak import ExportSnowBreak
from ..games.srmi import ExportSRMI
from ..games.unity import ExportUnity
from ..games.wwmi import ExportWWMI
from ..games.ntemi import ExportNTEMI
from ..games.yysls import ExportYYSLS
from ..games.zzmi import ExportZZMI
from ..games.zzmidx12 import ExportZZMIDX12

from ..model.blueprint_model import BluePrintModel
from ..blueprint.blueprint_export_helper import BlueprintExportHelper
from ..blueprint.blueprint_node_obj import ObjectPersistentIdManager


def _export_blueprint_model(blueprint_model):
    """Dispatch one parsed output layer to the selected game exporter."""
    if GlobalConfig.logic_name == LogicName.EFMI:
        ExportEFMI(blueprint_model=blueprint_model).export()
    elif GlobalConfig.logic_name == LogicName.GIMI:
        ExportGIMI(blueprint_model=blueprint_model).export()
    elif GlobalConfig.logic_name == LogicName.HIMI:
        ExportHIMI(blueprint_model=blueprint_model).export()
    elif GlobalConfig.logic_name == LogicName.IdentityV:
        ExportIdentityV(blueprint_model=blueprint_model).export()
    elif GlobalConfig.logic_name == LogicName.SRMI:
        ExportSRMI(blueprint_model=blueprint_model).export()
    elif GlobalConfig.logic_name == LogicName.ZZMIDX12:
        ExportZZMIDX12(blueprint_model=blueprint_model).export()
    elif GlobalConfig.logic_name == LogicName.ZZMI:
        ExportZZMI(blueprint_model=blueprint_model).export()
    elif GlobalConfig.logic_name == LogicName.WWMI:
        ExportWWMI(blueprint_model=blueprint_model).export()
    elif GlobalConfig.logic_name == LogicName.NTEMI:
        ExportNTEMI(blueprint_model=blueprint_model).export()
    elif GlobalConfig.logic_name == LogicName.SnowBreak:
        ExportSnowBreak(blueprint_model=blueprint_model).export()
    elif GlobalConfig.logic_name == LogicName.YYSLS:
        ExportYYSLS(blueprint_model=blueprint_model).export()
    elif GlobalConfig.logic_name in {
        LogicName.Naraka, LogicName.NarakaM, LogicName.GF2, LogicName.AILIMIT,
    }:
        ExportUnity(blueprint_model=blueprint_model).export()
    else:
        raise ValueError("当前游戏预设暂不支持生成Mod")


def _safe_output_config_name(node, index, used_names):
    raw_name = str(getattr(node, "ini_filename", "") or "").strip()
    if not raw_name:
        raw_name = f"{GlobalConfig.get_workspace_name()}_output_{index + 1}.cfg"
    raw_name = os.path.basename(raw_name.replace("\\", "/"))
    raw_name = re.sub(r"[^A-Za-z0-9_.-]", "_", raw_name)
    if not raw_name or raw_name in {".", ".."}:
        raw_name = f"{GlobalConfig.get_workspace_name()}_output_{index + 1}.cfg"
    stem, _ = os.path.splitext(raw_name)
    raw_name = stem + ".cfg"
    stem, extension = os.path.splitext(raw_name)
    candidate = raw_name
    suffix = 2
    while candidate.casefold() in used_names:
        candidate = f"{stem}_{suffix}{extension}"
        suffix += 1
    used_names.add(candidate.casefold())
    return candidate


def _prepend_ini_includes(ini_path, include_names):
    if not include_names:
        return
    with open(ini_path, "r", encoding="utf-8") as ini_file:
        body = ini_file.read()
    body = re.sub(r"\n;sha256=[0-9a-fA-F]+\s*\Z", "\n", body)
    # Replace a previous generated include block so repeated exports remain
    # stable instead of nesting the same references indefinitely.
    body = re.sub(
        r"\A; Generated by TheHerta4 SSMT chained includes\.\n\n\[Include\]\n"
        r"(?:include = [^\r\n]+\r?\n)+\r?\n?",
        "",
        body,
    )
    include_header = (
        "; Generated by TheHerta4 SSMT chained includes.\n\n"
        "[Include]\n"
        + "".join(f"include = {name}\n" for name in include_names)
        + "\n"
    )
    body = include_header + body.lstrip("\r\n")
    digest = hashlib.sha256(body.encode("utf-8")).hexdigest()
    with open(ini_path, "w", encoding="utf-8", newline="\n") as ini_file:
        ini_file.write(body.rstrip("\n") + f"\n\n;sha256={digest}\n\n")


def _write_ini_include_root(root_path, include_names):
    lines = ["; Generated by TheHerta4 SSMT chained output.", "", "[Include]"]
    lines.extend(f"include = {name}" for name in include_names)
    body = "\n".join(lines) + "\n"
    digest = hashlib.sha256(body.encode("utf-8")).hexdigest()
    with open(root_path, "w", encoding="utf-8", newline="\n") as ini_file:
        ini_file.write(body + f"\n;sha256={digest}\n\n")


def _generate_chained_mod(tree, context, output_chains):
    output_folder = GlobalConfig.path_generate_mod_folder()
    used_names = {(GlobalConfig.get_workspace_name() + ".ini").casefold()}
    terminal_ini_names = []
    output_index = 0

    for chain in output_chains:
        previous_ini_names = []
        for output_node in chain:
            config_name = _safe_output_config_name(output_node, output_index, used_names)
            output_index += 1
            stem = os.path.splitext(config_name)[0]
            GlobalConfig.generated_mod_name_override = stem
            BlueprintExportHelper.runtime_output_node = output_node
            blueprint_model = None
            try:
                blueprint_model = BluePrintModel(tree=tree, context=context, output_node=output_node)
                _export_blueprint_model(blueprint_model)
            finally:
                if blueprint_model is not None:
                    _cleanup_unico_temp_objects(blueprint_model)
                BlueprintExportHelper.runtime_output_node = None
                GlobalConfig.generated_mod_name_override = ""

            if GlobalConfig.logic_name == LogicName.WWMI:
                generated_files = sorted(glob.glob(os.path.join(output_folder, stem + "_*.ini")))
            else:
                generated_files = [os.path.join(output_folder, stem + ".ini")]
                generated_files = [path for path in generated_files if os.path.isfile(path)]
            if not generated_files:
                raise ValueError(f"输出节点 '{output_node.name}' 未生成 INI 文件")
            config_paths = []
            for generated_path in generated_files:
                config_path = os.path.splitext(generated_path)[0] + ".cfg"
                os.replace(generated_path, config_path)
                config_paths.append(config_path)
            generated_names = [os.path.basename(path) for path in config_paths]
            for config_path in config_paths:
                _prepend_ini_includes(config_path, previous_ini_names)
            previous_ini_names = generated_names

        terminal_ini_names.extend(previous_ini_names)

    _write_ini_include_root(
        os.path.join(output_folder, GlobalConfig.get_workspace_name() + ".ini"),
        terminal_ini_names,
    )


def generate_mod_from_tree(tree, context, report_callback):
    if not tree:
        report_callback({'ERROR'}, "未找到有效的蓝图")
        return {'CANCELLED'}

    TimerUtils.Start("GenerateMod Mod")

    # 每次生成 Mod 都必须重置全局按键计数，
    # 否则会沿用上一次导出的 $swapkey / $active 索引，导致本次 ini 变量编号错乱。
    GlobalConfig.initialize_key_count()
    BlueprintExportHelper.runtime_output_node = None
    BlueprintExportHelper.set_runtime_blueprint_tree(tree)

    # 导出前强制同步一次 Object Info 节点。
    # 蓝图后续解析主要仍读取 node.object_name，
    # 因此必须先通过持久 object_id 把改名后的真实物体名称回写到节点上，
    # 避免用户改名后蓝图仍使用旧名称导出。
    refresh_summary = ObjectPersistentIdManager.refresh_all_nodes(tree=tree, source="export")
    if refresh_summary["missing_count"] > 0:
        report_callback(
            {'WARNING'},
            f"导出前刷新了 {refresh_summary['updated_count']} 个物体节点，但有 {refresh_summary['missing_count']} 个节点未找到对应物体",
        )

    try:
        blueprint_model = BluePrintModel(tree=tree, context=context)
    except ValueError as error:
        TimerUtils.End("GenerateMod Mod")
        report_callback({'ERROR'}, str(error))
        return {'CANCELLED'}

    print("当前蓝图: " + str(blueprint_model))

    try:
        output_chains = BlueprintExportHelper.get_output_chains(tree)
        chained = len(output_chains) > 1 or any(len(chain) > 1 for chain in output_chains)
        if chained:
            _cleanup_unico_temp_objects(blueprint_model)
            _generate_chained_mod(tree, context, output_chains)
        else:
            _export_blueprint_model(blueprint_model)
    except (OSError, ValueError) as error:
        _cleanup_unico_temp_objects(blueprint_model)
        BlueprintExportHelper.runtime_output_node = None
        GlobalConfig.generated_mod_name_override = ""
        TimerUtils.End("GenerateMod Mod")
        report_callback({'ERROR'}, str(error))
        return {'CANCELLED'}

    TimerUtils.End("GenerateMod Mod")
    report_callback({'INFO'}, rpt_("生成Mod成功！"))
    CommandUtils.OpenGeneratedModFolder()
    return {'FINISHED'}


def _cleanup_unico_temp_objects(blueprint_model: BluePrintModel):
    """清理 UniComponent 拆分产生的临时物体"""
    temp_objects = getattr(blueprint_model, '_unico_temp_objects', None)
    if not temp_objects:
        return
    for temp_obj in temp_objects:
        try:
            if temp_obj and temp_obj.name in bpy.data.objects:
                bpy.data.objects.remove(temp_obj, do_unlink=True)
        except Exception as e:
            print(f"[UniComponent] 清理临时物体时出错: {e}")
    print(f"[UniComponent] 已清理 {len(temp_objects)} 个临时拆分物体")


class SSMTGenerateModBlueprint(bpy.types.Operator):
    bl_idname = "ssmt.generate_mod_blueprint"
    bl_label = "生成Mod"
    bl_description = "根据当前工作空间对应的蓝图架构生成对应的Mod文件"
    bl_options = {'REGISTER','UNDO'}

    def execute(self, context):
        tree = BlueprintExportHelper.get_current_blueprint_tree(context=context)
        if not tree:
            self.report({'ERROR'}, "未找到当前蓝图，请在蓝图编辑器中点击“生成Mod”")
            return {'CANCELLED'}
        return generate_mod_from_tree(tree=tree, context=context, report_callback=self.report)


class SSMTGenerateSelectedBlueprintMod(bpy.types.Operator):
    bl_idname = "ssmt.generate_selected_blueprint_mod"
    bl_label = "生成Mod"
    bl_description = "根据当前选中的蓝图快捷生成对应的Mod文件"
    bl_options = {'REGISTER', 'UNDO'}

    def execute(self, context):
        global_properties = getattr(getattr(context, "scene", None), "global_properties", None)
        selected_name = getattr(global_properties, "selected_blueprint_name", "") if global_properties else ""

        tree = BlueprintExportHelper.get_selected_blueprint_tree(
            selected_name=selected_name,
            context=context,
        )
        if not tree:
            self.report({'ERROR'}, "请选择有效的蓝图")
            return {'CANCELLED'}

        if global_properties and global_properties.selected_blueprint_name != tree.name:
            global_properties.selected_blueprint_name = tree.name

        return generate_mod_from_tree(tree=tree, context=context, report_callback=self.report)
    
def register():
    bpy.utils.register_class(SSMTGenerateModBlueprint)
    bpy.utils.register_class(SSMTGenerateSelectedBlueprintMod)


def unregister():
    bpy.utils.unregister_class(SSMTGenerateSelectedBlueprintMod)
    bpy.utils.unregister_class(SSMTGenerateModBlueprint)

